language: python
python:
  - "3.3"
  - "3.4"
  # - nightly
install:
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y install rsyslog
  - pip install -r requirements-tests.txt --use-mirrors
  - python setup.py develop
  - wget https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip
  - unzip 0.5.0_linux_amd64.zip
  - wget https://dl.bintray.com/mitchellh/vault/vault_0.1.2_linux_amd64.zip
  - unzip vault_0.1.2_linux_amd64.zip
before_script:
  - export PATH=$PATH:$PWD
script:
  - py.test
