language: python
python:
  - "3.3"
  - "3.4"
  # - nightly

env:
  global:
    - MYSQL_DSN='root:@tcp(127.0.0.1:3306)/'
    - PG_URL='user=postgres dbname=postgres sslmode=disable'

install:
  - sudo update-ca-certificates
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y install rsyslog
  - pip install -r requirements-tests.txt
  - pip install pytest pytest-cov pytest-pep8 coveralls
  - python setup.py develop
  - wget https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
  - unzip 0.5.2_linux_amd64.zip
  - wget https://dl.bintray.com/mitchellh/vault/vault_0.1.2_linux_amd64.zip
  - unzip vault_0.1.2_linux_amd64.zip
before_script:
  - export PATH=$PATH:$PWD
  - python tests/tls.py --directory --name server tls
  - python tests/tls.py --directory --name client tls
script:
  - py.test --pep8 aiovault -v --cov aiovault --cov-report term-missing tests
after_success:
  - coveralls
